#!/bin/bash/

#01: Get the list of the network interfaces of the machine without displaying
# any detail for these interfaces. Only the list of names.

ifconfig -l | tr ' ' '\n'

# ifconfig: network interface configurator
# -l: list all available interfaces
# tr - replace spaces with newlines