#!/bin/bash/

#02: Identify and display the Ethernet interface characteristics:
#a: Identify broadcast address

#: A broadcast address is a network address used to transmit to all devices
# connected to a multiple-access communications network

ifconfig en0 | grep broadcast | awk '{ print $6 }'

#b:  Identify all IP adresses which are part of the same subnet
arp -a | awk '{print $2}'

