#!/bin/bash/

#03: Identify the MAC address of the Wi-Fi card
# networksetup -listallhardwareports

# en1 = wifi port

ifconfig en1 | grep ether | awk '{print $2}'

#alternative: networksetup -getmacaddress en1 | awk '{print $3}'