#!/bin/bash/

#04: Identifiy the default gateway in the routing table

netstat -rn | grep 'default' -m1 | awk '{print $2}'

#netstat displays network related information
# -r shows the routing tables
# -n shows the network addresses as numbers instead of symbolically