#!/bin/bash/

#05: Identify the IP address of the DNS that responds to the url: who.int

#DNS = domain name system, the phone book of the internet. the DNS translates
# domain names (google.com, nytimes.com) to IP addresses so browsers can load
# internet resources

host who.int | grep address | cut -d ' ' -f4

#host = DNS lookup utility.
#alternative: dig who.int | awk '/ANSWER SECTION/{getline;print $5}'
#dig = DNS lookup utility
#awk searches for "answer section" the getline reads the next line
# alternative is: nslookup who.int | awk '/Name/{getline; print $2}'
#alternative: host who.int | awk 'NR==1 {print $4}'

#src: https://www.cloudflare.com/learning/dns/what-is-dns/