#!/bin/bash/

#08: Find the provider of who.int

#answer = Cloudflare,Inc.

# find the IP address of who.int with answer in 05:

ip_address=$(nslookup who.int | awk '/Name/{getline; print $2}')

# use IP address with
whois $ip_address | grep 'OrgName:'| awk '/OrgName/{print $2 $3}'
