#!/bin/bash/

#12:Find the IP that was assigned to you by dhcp server

ifconfig en0 | awk '/inet/{getline; print $2}'

#basically looking for the local IP address assigned by the 'router' - inet add

#A DHCP Server is a network server that automatically provides and assigns
#IP addresses, default gateways and other network parameters to client devices.
#It relies on the standard protocol known as Dynamic Host Configuration Protocol
# or DHCP to respond to broadcast queries by clients.