#!/bin/bash/

#15: Make the intra.42.fr address reroute to 46.19.122.85

#edit the /etc/hosts file so that it reads: 46.19.122.85 intra.42.fr

#(at hive, this would be editing the cdn.hive.fi like in the file)
#this is a protected system file, therefore need root priviledges (sudo)