#!/bin/bash/

#What command gives you the time since your system was last booted?

uptime -s

#uptime tells us how long the system has been running
#-s (since) tells us since when it was logged in.
#alternative: last reboot | head -1