#!/bin/bash/

#Name the command that determines the state of the SSH service.

sudo service ssh status

#alternatively: sudo systemctl status ssh

#src: https://linuxhint.com/check-if-ssh-is-running-on-linux/