#!/bin/bash/

#What file contains the RSA keys of systems that are authorized to connect via SSH?

~/.ssh/authorized_keys

# src: https://www.digitalocean.com/community/tutorials/ssh-essentials-working-with-ssh-servers-clients-and-keys