#!/bin/bash/

#What command lets you know who is connected to the System?

whoami

#alternatively w
#alternatively who
#src https://www.thegeekstuff.com/2009/03/4-ways-to-identify-who-is-logged-in-on-your-linux-system/