#!/bin/bash/
# Run the ‘tail -f /var/log/syslog‘ command in background

sudo tail -f /var/log/syslog &

# & sign forces process to run in the background
#src: https://www.tecmint.com/run-linux-command-process-in-background-detach-process/

#run jobs -l to see the processes running in the background