#!/bin/bash/
#Find the command that kills the background command’s process

sudo kill $pid
#aternatively sudo kill -9 tail (-9 closes process with the name that follows)
#$pid - process id number given when program is run. (can find with jobs -l)

#https://www.cyberciti.biz/faq/how-to-check-running-process-in-linux-using-command-line/