#!/bin/bash/

sudo kill $pid

#Find the command that kills the background command’s process

#https://www.cyberciti.biz/faq/how-to-check-running-process-in-linux-using-command-line/

#$pid - process id number given when program is run. (can find with jobs -l)