#!/bin/bash/

#Find the service which makes it possible to run specific tasks following a
#regular schedule

cron

#daemon to execute scheduled commands

#src: https://www.makeuseof.com/tag/linux-task-scheduling-crontab-explained/
