#!/bin/bash/

#Find the service which makes it possible to run specific tasks following a
#regular schedule

cron

#daemon to execute scheduled commands
#once set up, cron starts automatically from /etc/init.d

#src: https://www.makeuseof.com/tag/linux-task-scheduling-crontab-explained/
