#!/bin/bash/

#Find the command that allows you to connect via ssh on the VM.
# (In parallel with the graphic session)

check up on this

#src https://wpguru.co.uk/2014/02/how-to-ssh-into-a-virtual-machine-in-parallels-desktop/