#!/bin/bash/

#Find the command that kills ssh service

sudo service ssh stop

#srcs: https://www.cyberciti.biz/faq/howto-start-stop-ssh-server/

#to stop the ssh indefinitely: sudo systemctl disable ssh