#!/bin/bash/

#List all real users on the VM

awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd

#src: https://askubuntu.com/questions/257421/list-all-human-users

#-F uses the character following it as the input field separator